### ISSUE TITLE
Error: lexical error: invalid char in json text. when using wm_name2id_()

### ISSUE THREAD

**Issue by KatLeigh11** [ropensci/worrms#24]
Hi there!

I am trying to use wm_name2id_() and getting a very strange error. Can you help me understand why? This error did not occur with another set of names, only this set triggered the error. See file in link (referred to as 'all_children$child' in the code segment below) for the names I am passing to wm_name2id_() that results in this error. Thanks for the help!

> child_AID <- wm_name2id_(all_children$child)
Error: lexical error: invalid char in json text.
                                       <html><body><h1>400 Bad request
                     (right here) ------^

https://drive.google.com/file/d/1KBx-pG_h-fK5Rw1RY4feHhbwteEdlkMs/view?usp=sharing

P.S. I already tried encoding the names as "UTF-8", but that didn't seem to help.

**Comment by bart-v** [comment]
Hi,

We checked the server, and cannot find any "HTTP 400 Bad request" response.
Maybe retry?

**Comment by KatLeigh11** [comment]
I did. Same error. Did you try running the code with that CSV file I sent? cuz it's that specific list of names that seems to trigger the error.

![image](https://user-images.githubusercontent.com/56566722/126846592-156d651b-36d6-404f-a54d-b13449920ba3.png)

**Comment by KatLeigh11** [comment]
FYI, I did a re-try and also tried another set of names. These ones also errored. So I have two sets of names that worked, and two that yielded errors. Here is the other set that threw an error: https://drive.google.com/file/d/13cn2xC85FWApi8-rd4-Q5L77z_AYCZ9Y/view?usp=sharing

**Comment by bart-v** [comment]
* Your screenshot has "Ophiopholis longispina" while none of your files has this name, looks suspicious :)
* The only way to know what is causing this is to use `wm_name2id` (without underscore) in a loop, and see on what entry it fails

**Comment by bart-v** [comment]
No more feedback, assume fixed, closing

**Comment by jebyrnes** [comment]
Hello! Wanted to re-open with an oddity. My colleague @jbburant and I are working off of the same code.

```
wm_name2id("Saccharina latissima")
```

Works for me, but, he gets a 400 bad request error

```
Error: (400) Bad Request - Saccharina latissima
```

Using `wm_name2id_` he gets the same bad request error at the top of this thread. For me, it goes through just fine.

Why the inconsistency? Is there something in our setup that would lead to these different results.

**Comment by jebyrnes** [comment]
We dug deep into the code to the point of when crul calls in the request - that is where it fails.

The only difference we could find is that in the output. His is

```
<crul response> 
  url: https://www.marinespecies.org/rest/AphiaIDByName/Saccharina latissima
  request_headers: 
    User-Agent: libcurl/7.64.1 r-curl/4.3.2 crul/1.1.0
    Accept-Encoding: gzip, deflate
    Accept: application/json, text/xml, application/xml, */*
  response_headers: 
    status: HTTP/2 400
    cache-control: no-cache
    content-type: text/html
  status: 400
```

In mind, libcurl is 7.77.0. I assume this might be the issue? We're going to try and use homebrew to get a newer version of curl, but, could this really be the issue here?
